### ISSUE TITLE
Problem running assign_taxonomy.py

### ISSUE THREAD

**Issue by micro-mario** [LangilleLab/microbiome_helper#24]
Good evening,

I am working with ITS1 for fungal classification. The pipeline has been working great so far, but at the time of assigning the taxonomy it doesn't work, receiving a KeyError: 'assignments'. I have tried to edit the taxonomy file, so there are no spaces and I've added ";" to all the lines, following the mothur nomenclature, which seems to have been the same problem that some other people have had. Nevertheless, it hasn't worked in my case.

Please find the message I receive:
mh_user@MicrobiomeHelper:~/fungi_svna$ assign_taxonomy.py -i ~/fungi_svna/clustering/rep_set.fna -t /home/shared/rRNA_db/sh_taxonomy_qiime_ver7_97_s_01.12.2017.txt -r /home/shared/rRNA_db/sh_refs_qiime_ver7_97_s_01.12.2017.fasta -m mothur -o assigned_manually
Traceback (most recent call last):
  File "/home/mh_user/anaconda2/envs/qiime1/bin/assign_taxonomy.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'assign_taxonomy.py')
  File "/home/mh_user/anaconda2/envs/qiime1/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
    
  File "/home/mh_user/anaconda2/envs/qiime1/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
    
  File "/home/mh_user/anaconda2/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/assign_taxonomy.py", line 417, in <module>
    main()
  File "/home/mh_user/anaconda2/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/assign_taxonomy.py", line 394, in main
    log_path=log_path)
  File "/home/mh_user/anaconda2/envs/qiime1/lib/python2.7/site-packages/qiime/assign_taxonomy.py", line 791, in __call__
    tmp_dir=get_qiime_temp_dir()
  File "/home/mh_user/anaconda2/envs/qiime1/lib/python2.7/site-packages/burrito_fillings-0.1.1-py2.7.egg/bfillings/mothur.py", line 578, in mothur_classify_file
KeyError: 'assignments'

I have also updates all my packages in case that the problem was with old version of packages. But it hasn't worked either, so I don't know what else I can do!

Thanks,
Mario

**Comment by gavinmdouglas** [comment]
Hi Mario,

Sorry for my late response, but has this problem been resolved? I believe your issue is related to this post: https://github.com/biocore/qiime/pull/1025

**Comment by micro-mario** [comment]
?Hi Gavin!


Thanks for your reply. Yes, it's been sorted now!

Chers!


Dr Mario Toubes Rodrigo FRGS
Programme Support Tutor
Office hours: Tuesdays 15-17  / Wednesdays 16-17
E441  John Dalton East
School of Science and the Environment
Manchester Metropolitan University

________________________________

**Comment by gavinmdouglas** [comment]
I'm glad to hear that!
