### ISSUE TITLE
ModuleNotFoundError: No module named 'biom'?

### ISSUE THREAD

**Issue by arsilan324** [LangilleLab/microbiome_helper#51]
Hi there,
I want to use FAPROTAX but when I run the command, i get the following error

```
Traceback (most recent call last):
  File "./collapse_table.py", line 65, in <module>
    import biom
ModuleNotFoundError: No module named 'biom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./collapse_table.py", line 70, in <module>
    if e.message != 'No module named %s'%(name):
AttributeError: 'ModuleNotFoundError' object has no attribute 'message'

```
Can you please help?
Thanks

**Comment by gavinmdouglas** [comment]
Just seeing this now sorry, but if anyone else is having similar issues that error means that you need to install the biom-format package.
